-- ================================================================================
-- PostgreSQL Schema
-- ================================================================================

DROP TABLE IF EXISTS release_docs;

CREATE TABLE release_docs (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             VARCHAR(255) NOT NULL,
    env                 INTEGER      NOT NULL,  -- 环境: uat=1,prod=2
    kind                INTEGER      NOT NULL,  -- 类型: sprint=1,hotfix=2
    project_type        INTEGER      NOT NULL,  -- 项目类型: onchain=1,offchain=2,frontend=3,backend=4,risk=5,settlement=6
    is_ready            BOOLEAN      NOT NULL DEFAULT FALSE,

    release_plans       JSONB,
    release_notes       JSONB,
    db_access_tickets   JSONB,
    sql_review_tickets  JSONB,
    checklists          JSONB,

    is_delete           BOOLEAN      NOT NULL  DEFAULT FALSE,
    created_at          timestamptz  NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz  NULL,
    creator             INTEGER      NOT NULL,
    updator             INTEGER      NULL
);

CREATE INDEX idx_release_docs_env           ON release_docs (env);
CREATE INDEX idx_release_docs_kind          ON release_docs (kind);
CREATE INDEX idx_release_docs_project_type  ON release_docs (project_type);
CREATE INDEX idx_release_docs_is_ready      ON release_docs (is_ready);
CREATE INDEX idx_release_docs_is_delete     ON release_docs (is_delete);


COMMENT ON TABLE release_docs IS '发布文档表';


COMMENT ON COLUMN release_docs.version IS '版本号';
COMMENT ON COLUMN release_docs.env IS '环境: uat=1,prod=2';
COMMENT ON COLUMN release_docs.kind IS '类型: sprint=1,hotfix=2';
COMMENT ON COLUMN release_docs.project_type IS '项目类型: onchain=1,offchain=2,frontend=3,backend=4,risk=5,settlement=6';
COMMENT ON COLUMN release_docs.is_ready IS '是否准备好发布';

COMMENT ON COLUMN release_docs.release_plans IS '发布计划数组';
COMMENT ON COLUMN release_docs.release_notes IS '发布说明数组';
COMMENT ON COLUMN release_docs.db_access_tickets IS '数据库访问工单数组';
COMMENT ON COLUMN release_docs.sql_review_tickets IS 'SQL审核工单数组';
COMMENT ON COLUMN release_docs.checklists IS '检查清单数组';

COMMENT ON COLUMN release_docs.is_delete IS '是否删除';
COMMENT ON COLUMN release_docs.created_at IS '创建时间';
COMMENT ON COLUMN release_docs.updated_at IS '更新时间';
COMMENT ON COLUMN release_docs.creator IS '创建人ID';
COMMENT ON COLUMN release_docs.updator IS '更新人ID';
